name: Deploy Portfolio to AWS S3

# Run this workflow on a push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code from your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Step 4: Run Terraform to create the infrastructure
      - name: Terraform Apply
        run: |
          terraform init
          terraform apply -auto-approve

      # Step 5: Sync the website files to the S3 bucket
      - name: Deploy site to S3 bucket
        # We get the bucket name from the terraform output
        run: aws s3 sync . s3://$(terraform output -raw bucket_name) --delete